import SwiftUI

/// Displays an enriched document generated by Hermes from note directives.
struct EnrichedDocumentView: View {
    let result: EnrichmentResult
    let isEditingCopy: Bool
    var onEditCopy: (() -> Void)?

    @State private var showExportSheet = false

    init(
        result: EnrichmentResult,
        isEditingCopy: Bool = false,
        onEditCopy: (() -> Void)? = nil
    ) {
        self.result = result
        self.isEditingCopy = isEditingCopy
        self.onEditCopy = onEditCopy
    }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: Design.Spacing.lg) {
                // Header with title and stale warning
                headerSection

                // AI-generated content warning
                aiWarningBanner

                // Stale indicator
                if result.isStale {
                    staleBanner
                }

                // Markdown content
                markdownSection

                // Structured sections
                if !result.sections.isEmpty {
                    sectionsList
                }

                // Citations
                if !result.citations.isEmpty {
                    citationsSection
                }

                // Metadata footer
                metadataFooter
            }
            .padding(Design.Spacing.md)
        }
        .toolbar {
            ToolbarItemGroup(placement: .topBarTrailing) {
                Button {
                    showExportSheet = true
                } label: {
                    Image(systemName: "square.and.arrow.up")
                }
                .accessibilityLabel("Export document")

                if !isEditingCopy, let onEditCopy {
                    Button {
                        onEditCopy()
                    } label: {
                        Image(systemName: "doc.badge.plus")
                    }
                    .accessibilityLabel("Edit as derived copy")
                }
            }
        }
        .sheet(isPresented: $showExportSheet) {
            NoteExportSheet(result: result)
        }
    }

    // MARK: - Header

    private var headerSection: some View {
        VStack(alignment: .leading, spacing: Design.Spacing.xs) {
            Text(result.title)
                .font(Design.Typography.screenTitle2)
                .foregroundStyle(Design.Colors.foreground)

            HStack(spacing: Design.Spacing.xxs) {
                Image(systemName: "cpu")
                    .font(Design.Typography.caption)
                    .foregroundStyle(Design.Colors.secondaryForeground)
                Text("Generated by Hermes")
                    .font(Design.Typography.caption)
                    .foregroundStyle(Design.Colors.secondaryForeground)
            }
        }
    }

    // MARK: - Warnings

    private var aiWarningBanner: some View {
        HStack(spacing: Design.Spacing.sm) {
            Image(systemName: "exclamationmark.triangle.fill")
                .foregroundStyle(Design.Colors.warning)
                .font(.system(size: Design.Size.iconSmall))

            Text("This is AI-generated content. Verify important information before relying on it.")
                .font(Design.Typography.caption)
                .foregroundStyle(Design.Colors.secondaryForeground)
        }
        .padding(Design.Spacing.sm)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Design.Colors.warning.opacity(0.1))
        .clipShape(RoundedRectangle(cornerRadius: Design.CornerRadius.sm))
        .accessibilityElement(children: .combine)
        .accessibilityLabel("AI-generated content warning")
    }

    private var staleBanner: some View {
        HStack(spacing: Design.Spacing.sm) {
            Image(systemName: "arrow.triangle.2.circlepath")
                .foregroundStyle(Design.Colors.warning)
                .font(.system(size: Design.Size.iconSmall))

            VStack(alignment: .leading, spacing: 2) {
                Text("Source has changed since enrichment")
                    .font(Design.Typography.caption)
                    .fontWeight(.medium)
                    .foregroundStyle(Design.Colors.warning)
                Text("Drawing rev \(result.sourceDrawingRevision), text rev \(result.sourceTextRevision)")
                    .font(Design.Typography.caption2)
                    .foregroundStyle(Design.Colors.secondaryForeground)
            }
        }
        .padding(Design.Spacing.sm)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Design.Colors.warning.opacity(0.08))
        .clipShape(RoundedRectangle(cornerRadius: Design.CornerRadius.sm))
        .accessibilityElement(children: .combine)
        .accessibilityLabel("Stale document: source has changed")
    }

    // MARK: - Content

    private var markdownSection: some View {
        VStack(alignment: .leading, spacing: Design.Spacing.sm) {
            Text(result.markdown)
                .font(Design.Typography.body)
                .foregroundStyle(Design.Colors.foreground)
                .textSelection(.enabled)
        }
    }

    private var sectionsList: some View {
        VStack(alignment: .leading, spacing: Design.Spacing.md) {
            ForEach(result.sections) { section in
                VStack(alignment: .leading, spacing: Design.Spacing.xs) {
                    HStack(spacing: Design.Spacing.xxs) {
                        Image(systemName: section.kind == .summary ? "doc.text" : "tag.fill")
                            .font(Design.Typography.caption)
                            .foregroundStyle(Design.Brand.accent)
                        Text(section.title)
                            .font(Design.Typography.headline)
                            .foregroundStyle(Design.Colors.foreground)
                    }

                    Text(section.markdown)
                        .font(Design.Typography.body)
                        .foregroundStyle(Design.Colors.foreground)
                        .textSelection(.enabled)
                }
                .padding(Design.Spacing.sm)
                .background(Design.Colors.surface)
                .clipShape(RoundedRectangle(cornerRadius: Design.CornerRadius.sm))
            }
        }
    }

    // MARK: - Citations

    private var citationsSection: some View {
        VStack(alignment: .leading, spacing: Design.Spacing.sm) {
            Label("Citations", systemImage: "text.quote")
                .font(Design.Typography.headline)
                .foregroundStyle(Design.Colors.foreground)

            ForEach(result.citations) { citation in
                HStack(alignment: .top, spacing: Design.Spacing.sm) {
                    Image(systemName: "link")
                        .font(Design.Typography.caption)
                        .foregroundStyle(Design.Brand.accent)
                        .padding(.top, 2)

                    VStack(alignment: .leading, spacing: 2) {
                        if let url = citation.url, let linkURL = URL(string: url) {
                            Link(citation.title, destination: linkURL)
                                .font(Design.Typography.callout)
                                .foregroundStyle(Design.Brand.accent)
                        } else {
                            Text(citation.title)
                                .font(Design.Typography.callout)
                                .foregroundStyle(Design.Colors.foreground)
                        }

                        Text("Accessed \(citation.accessedAt.formatted(date: .abbreviated, time: .shortened))")
                            .font(Design.Typography.caption2)
                            .foregroundStyle(Design.Colors.secondaryForeground)
                    }
                }
                .padding(.vertical, Design.Spacing.xxs)
            }
        }
        .padding(Design.Spacing.md)
        .background(Design.Colors.surface)
        .clipShape(RoundedRectangle(cornerRadius: Design.CornerRadius.md))
    }

    // MARK: - Metadata Footer

    private var metadataFooter: some View {
        VStack(alignment: .leading, spacing: Design.Spacing.xs) {
            Divider()

            HStack {
                VStack(alignment: .leading, spacing: 2) {
                    Text("Run ID")
                        .font(Design.Typography.caption2)
                        .foregroundStyle(Design.Colors.secondaryForeground)
                    Text(result.runId.uuidString.prefix(8) + "...")
                        .font(Design.Typography.caption)
                        .foregroundStyle(Design.Colors.tertiaryForeground)
                        .textSelection(.enabled)
                }

                Spacer()

                VStack(alignment: .trailing, spacing: 2) {
                    Text("Created")
                        .font(Design.Typography.caption2)
                        .foregroundStyle(Design.Colors.secondaryForeground)
                    Text(result.createdAt.formatted(date: .abbreviated, time: .shortened))
                        .font(Design.Typography.caption)
                        .foregroundStyle(Design.Colors.tertiaryForeground)
                }
            }

            // Per-directive results
            if !result.commandResults.isEmpty {
                VStack(alignment: .leading, spacing: Design.Spacing.xxs) {
                    Text("Directive Results")
                        .font(Design.Typography.caption2)
                        .foregroundStyle(Design.Colors.secondaryForeground)

                    ForEach(result.commandResults) { cmdResult in
                        HStack(spacing: Design.Spacing.xxs) {
                            Image(systemName: cmdResult.status == .completed ? "checkmark.circle.fill" : "exclamationmark.circle.fill")
                                .font(.system(size: 10))
                                .foregroundStyle(cmdResult.status == .completed ? Design.Colors.success : Design.Colors.danger)
                            Text(cmdResult.directiveId.prefix(8) + "...")
                                .font(Design.Typography.caption2)
                                .foregroundStyle(Design.Colors.tertiaryForeground)
                            Text(cmdResult.status.rawValue)
                                .font(Design.Typography.caption2)
                                .foregroundStyle(Design.Colors.secondaryForeground)
                        }
                    }
                }
            }

            // Warnings
            if !result.warnings.isEmpty {
                VStack(alignment: .leading, spacing: Design.Spacing.xxs) {
                    Text("Warnings")
                        .font(Design.Typography.caption2)
                        .foregroundStyle(Design.Colors.warning)

                    ForEach(result.warnings, id: \.self) { warning in
                        HStack(spacing: Design.Spacing.xxs) {
                            Image(systemName: "exclamationmark.triangle")
                                .font(.system(size: 10))
                                .foregroundStyle(Design.Colors.warning)
                            Text(warning)
                                .font(Design.Typography.caption2)
                                .foregroundStyle(Design.Colors.secondaryForeground)
                        }
                    }
                }
            }
        }
    }
}
