#!/bin/bash
# Pre-archive entitlements verification gate
# Herald B38 §2.2b — run BEFORE xcodebuild archive
# Ensures the source entitlements file is git-clean and carries all required keys.
# The entitlements file is REGENERATED by xcodegen from project.yml properties;
# a dirty or incomplete file here means something stripped it between xcodegen and archive.
set -euo pipefail

cd ~/Herald

# Gate 1: file must be git-clean (no unstaged changes)
if ! git diff --quiet Herald/Kallisti.entitlements; then
    echo "FATAL: Herald.entitlements is dirty — unstaged changes detected:"
    git diff Herald/Kallisti.entitlements
    exit 1
fi
if ! git diff --cached --quiet Herald/Kallisti.entitlements; then
    echo "FATAL: Herald.entitlements is dirty — staged changes detected:"
    git diff --cached Herald/Kallisti.entitlements
    exit 1
fi

# Gate 2: all six required keys must be present in the source file
REQUIRED_KEYS=(
    com.apple.developer.healthkit
    com.apple.developer.healthkit.access
    com.apple.developer.healthkit.background-delivery
    aps-environment
    com.apple.developer.siri
    com.apple.security.application-groups
)

for key in "${REQUIRED_KEYS[@]}"; do
    if ! plutil -p Herald/Kallisti.entitlements | grep -q "$key"; then
        echo "FATAL: '$key' missing from source entitlements file Herald/Kallisti.entitlements"
        echo "Current contents:"
        plutil -p Herald/Kallisti.entitlements
        exit 1
    fi
done

echo "SOURCE ENTITLEMENTS OK"

# ── Build 31: signed artifact verification ───────────────────────────────────
# Gate 3: if a .xcarchive exists, verify the signed binary retains all keys.
ARCHIVE_PATH="${ARCHIVE_PATH:-${HOME}/Hermes-iOS-Builds/archives/Kallisti_0.1.0_b4.xcarchive}"
ARCHIVE_APP="${ARCHIVE_PATH}/Products/Applications/Kallisti.app"

if [ -d "$ARCHIVE_APP" ]; then
    echo ""
    echo "=== VERIFYING SIGNED ARCHIVE ==="
    ENTITLEMENTS_DUMP=$(codesign -d --entitlements :- "$ARCHIVE_APP" 2>&1)
    if [ $? -ne 0 ]; then
        echo "FATAL: codesign failed on archived app — the binary may be unsigned or ad-hoc"
        echo "$ENTITLEMENTS_DUMP"
        exit 1
    fi

    for key in "${REQUIRED_KEYS[@]}"; do
        if ! echo "$ENTITLEMENTS_DUMP" | grep -q "$key"; then
            echo "FATAL: '$key' missing from SIGNED archive entitlements"
            echo "Signed entitlements:"
            echo "$ENTITLEMENTS_DUMP" | plutil -p - 2>/dev/null || echo "$ENTITLEMENTS_DUMP"
            exit 1
        fi
    done

    # Also verify the embedded provisioning profile authorizes HealthKit
    EMBEDDED_PROFILE="${ARCHIVE_APP}/embedded.mobileprovision"
    if [ -f "$EMBEDDED_PROFILE" ]; then
        PROFILE_DUMP=$(security cms -D -i "$EMBEDDED_PROFILE" 2>/dev/null)
        if ! echo "$PROFILE_DUMP" | grep -q "com.apple.developer.healthkit"; then
            echo "FATAL: embedded provisioning profile does NOT authorize HealthKit"
            exit 1
        fi
        echo "  embedded.mobileprovision: HealthKit authorized"
    fi

    echo "SIGNED ARCHIVE ENTITLEMENTS OK"
else
    echo ""
    echo "NOTE: No archive found at $ARCHIVE_PATH — signed binary verification skipped."
    echo "  To verify a signed artifact, set ARCHIVE_PATH or IPA_PATH and rerun."
fi

# Gate 4: if an .ipa path is set, unzip and verify the exported app.
IPA_PATH="${IPA_PATH:-}"
if [ -n "$IPA_PATH" ] && [ -f "$IPA_PATH" ]; then
    TMP_IPA_DIR=$(mktemp -d /tmp/kallisti-ipa-verify-XXXXXX)
    unzip -q "$IPA_PATH" -d "$TMP_IPA_DIR"
    IPA_APP=$(find "$TMP_IPA_DIR" -name "*.app" -type d | head -1)

    if [ -n "$IPA_APP" ]; then
        echo ""
        echo "=== VERIFYING EXPORTED IPA ==="
        IPA_ENTITLEMENTS=$(codesign -d --entitlements :- "$IPA_APP" 2>&1)
        if [ $? -ne 0 ]; then
            echo "FATAL: codesign failed on exported IPA app"
            echo "$IPA_ENTITLEMENTS"
            rm -rf "$TMP_IPA_DIR"
            exit 1
        fi

        for key in "${REQUIRED_KEYS[@]}"; do
            if ! echo "$IPA_ENTITLEMENTS" | grep -q "$key"; then
                echo "FATAL: '$key' missing from exported IPA entitlements"
                echo "$IPA_ENTITLEMENTS" | plutil -p - 2>/dev/null || echo "$IPA_ENTITLEMENTS"
                rm -rf "$TMP_IPA_DIR"
                exit 1
            fi
        done

        # Profile check in exported IPA
        IPA_PROFILE=$(find "$TMP_IPA_DIR" -name "embedded.mobileprovision" -type f | head -1)
        if [ -f "$IPA_PROFILE" ]; then
            PROFILE_DUMP=$(security cms -D -i "$IPA_PROFILE" 2>/dev/null)
            if ! echo "$PROFILE_DUMP" | grep -q "com.apple.developer.healthkit"; then
                echo "FATAL: exported IPA profile does NOT authorize HealthKit"
                rm -rf "$TMP_IPA_DIR"
                exit 1
            fi
            echo "  IPA embedded.mobileprovision: HealthKit authorized"
        fi

        echo "EXPORTED IPA ENTITLEMENTS OK"
    fi

    rm -rf "$TMP_IPA_DIR"
fi
