#!/bin/bash
# Pre-archive entitlements verification gate
# Herald B38 §2.2b — run BEFORE xcodebuild archive
# Ensures the source entitlements file is git-clean and carries all required keys.
# The entitlements file is REGENERATED by xcodegen from project.yml properties;
# a dirty or incomplete file here means something stripped it between xcodegen and archive.
set -euo pipefail

cd ~/Herald-b34

# Gate 1: file must be git-clean (no unstaged changes)
if ! git diff --quiet Herald/Herald.entitlements; then
    echo "FATAL: Herald.entitlements is dirty — unstaged changes detected:"
    git diff Herald/Herald.entitlements
    exit 1
fi
if ! git diff --cached --quiet Herald/Herald.entitlements; then
    echo "FATAL: Herald.entitlements is dirty — staged changes detected:"
    git diff --cached Herald/Herald.entitlements
    exit 1
fi

# Gate 2: all six required keys must be present in the source file
REQUIRED_KEYS=(
    com.apple.developer.healthkit
    com.apple.developer.healthkit.access
    com.apple.developer.healthkit.background-delivery
    aps-environment
    com.apple.developer.siri
    com.apple.security.application-groups
)

for key in "${REQUIRED_KEYS[@]}"; do
    if ! plutil -p Herald/Herald.entitlements | grep -q "$key"; then
        echo "FATAL: '$key' missing from source entitlements file Herald/Herald.entitlements"
        echo "Current contents:"
        plutil -p Herald/Herald.entitlements
        exit 1
    fi
done

echo "SOURCE ENTITLEMENTS OK"
